In [16]:
# import all modules
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [17]:
# import dataset
# df = pd.read_csv('/content/drive/MyDrive/datasets/StressLevelDataset.csv')
# df.head()

In [24]:
# import dataset
df = pd.read_csv('/content/drive/MyDrive/datasets/coaster_db.csv')
df.head(10)

,coaster_name,Length,Speed,Location,Status,Opening date,Type,Manufacturer,Height restriction,Model,...,speed1,speed2,speed1_value,speed1_unit,speed_mph,height_value,height_unit,height_ft,Inversions_clean,Gforce_clean
0,Switchback Railway,600 ft (180 m),6 mph (9.7 km/h),Coney Island,Removed,"June 16, 1884",Wood,LaMarcus Adna Thompson,NaN,Lift Packed,...,6 mph,9.7 km/h,6.0,mph,6.0,50.0,ft,NaN,0,2.9
1,Flip Flap Railway,NaN,NaN,Sea Lion Park,Removed,1895,Wood,Lina Beecher,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,12.0
2,Switchback Railway (Euclid Beach Park),NaN,NaN,"Cleveland, Ohio, United States",Closed,NaN,Other,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
3,Loop the Loop (Coney Island),NaN,NaN,Other,Removed,1901,Steel,Edwin Prescott,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN
4,Loop the Loop (Young's Pier),NaN,NaN,Other,Removed,1901,Steel,Edwin Prescott,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN
5,Cannon Coaster,NaN,NaN,Coney Island,Removed,1902,Wood,George Francis Meyer,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,40.0,ft,NaN,0,NaN
6,Leap-The-Dips,"1,452 ft (443 m)",10 mph (16 km/h),Lakemont Park,Operating,1902,Wood – Side friction,Federal Construction Company,NaN,NaN,...,10 mph,16 km/h,10.0,mph,10.0,41.0,ft,NaN,0,NaN
7,Figure Eight (Euclid Beach Park),NaN,NaN,"Cleveland, Ohio, United States",Closed,NaN,Other,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
8,Drop the Dip,NaN,NaN,Coney Island,Removed,"June 6, 1907",Other,Arthur Jarvis,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,60.0,ft,NaN,0,NaN
9,Scenic Railway (Euclid Beach Park),NaN,NaN,"Cleveland, Ohio, United States",Closed,NaN,Other,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN

In [19]:
df.shape

(1087, 56)

In [20]:
# see all colums and their d-type
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1087 entries, 0 to 1086
Data columns (total 56 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   coaster_name                   1087 non-null   object
 1   Length                         953 non-null    object
 2   Speed                          937 non-null    object
 3   Location                       1087 non-null   object
 4   Status                         874 non-null    object
 5   Opening date                   837 non-null    object
 6   Type                           1087 non-null   object
 7   Manufacturer                   1028 non-null   object
 8   Height restriction             831 non-null    object
 9   Model                          744 non-null    object
 10  Height                         965 non-null    object
 11  Inversions                     932 non-null    float64
 12  Lift/launch system             795 non-null    object
 13  Cost                           382 non-null    object
 14  Trains                         718 non-null    object
 15  Park section                   487 non-null    object
 16  Duration                       765 non-null    object
 17  Capacity                       575 non-null    object
 18  G-force                        362 non-null    object
 19  Designer                       578 non-null    object
 20  Max vertical angle             357 non-null    object
 21  Drop                           494 non-null    object
 22  Soft opening date              96 non-null     object
 23  Fast Lane available            69 non-null     object
 24  Replaced                       173 non-null    object
 25  Track layout                   335 non-null    object
 26  Fastrack available             19 non-null     object
 27  Soft opening date.1            96 non-null     object
 28  Closing date                   236 non-null    object
 29  Opened                         27 non-null     object
 30  Replaced by                    88 non-null     object
 31  Website                        87 non-null     object
 32  Flash Pass Available           50 non-null     object
 33  Must transfer from wheelchair  106 non-null    object
 34  Theme                          44 non-null     object
 35  Single rider line available    81 non-null     object
 36  Restraint Style                22 non-null     object
 37  Flash Pass available           46 non-null     object
 38  Acceleration                   60 non-null     object
 39  Restraints                     24 non-null     object
 40  Name                           35 non-null     object
 41  year_introduced                1087 non-null   int64
 42  latitude                       812 non-null    float64
 43  longitude                      812 non-null    float64
 44  Type_Main                      1087 non-null   object
 45  opening_date_clean             837 non-null    object
 46  speed1                         937 non-null    object
 47  speed2                         935 non-null    object
 48  speed1_value                   937 non-null    float64
 49  speed1_unit                    937 non-null    object
 50  speed_mph                      937 non-null    float64
 51  height_value                   965 non-null    float64
 52  height_unit                    965 non-null    object
 53  height_ft                      171 non-null    float64
 54  Inversions_clean               1087 non-null   int64
 55  Gforce_clean                   362 non-null    float64
dtypes: float64(8), int64(2), object(46)
memory usage: 475.7+ KB

In [22]:
df.dtypes

coaster_name                      object
Length                            object
Speed                             object
Location                          object
Status                            object
Opening date                      object
Type                              object
Manufacturer                      object
Height restriction                object
Model                             object
Height                            object
Inversions                       float64
Lift/launch system                object
Cost                              object
Trains                            object
Park section                      object
Duration                          object
Capacity                          object
G-force                           object
Designer                          object
Max vertical angle                object
Drop                              object
Soft opening date                 object
Fast Lane available               object
Replaced                          object
Track layout                      object
Fastrack available                object
Soft opening date.1               object
Closing date                      object
Opened                            object
Replaced by                       object
Website                           object
Flash Pass Available              object
Must transfer from wheelchair     object
Theme                             object
Single rider line available       object
Restraint Style                   object
Flash Pass available              object
Acceleration                      object
Restraints                        object
Name                              object
year_introduced                    int64
latitude                         float64
longitude                        float64
Type_Main                         object
opening_date_clean                object
speed1                            object
speed2                            object
speed1_value                     float64
speed1_unit                       object
speed_mph                        float64
height_value                     float64
height_unit                       object
height_ft                        float64
Inversions_clean                   int64
Gforce_clean                     float64
dtype: object

In [23]:
df.describe()

,Inversions,year_introduced,latitude,longitude,speed1_value,speed_mph,height_value,height_ft,Inversions_clean,Gforce_clean
count,932.000000,1087.000000,812.000000,812.000000,937.000000,937.000000,965.000000,171.000000,1087.000000,362.000000
mean,1.547210,1994.986201,38.373484,-41.595373,53.850374,48.617289,89.575171,101.996491,1.326587,3.824006
std,2.114073,23.475248,15.516596,72.285227,23.385518,16.678031,136.246444,67.329092,2.030854,0.989998
min,0.000000,1884.000000,-48.261700,-123.035700,5.000000,5.000000,4.000000,13.100000,0.000000,0.800000
25%,0.000000,1989.000000,35.031050,-84.552200,40.000000,37.300000,44.000000,51.800000,0.000000,3.400000
50%,0.000000,2000.000000,40.289800,-76.653600,50.000000,49.700000,79.000000,91.200000,0.000000,4.000000
75%,3.000000,2010.000000,44.799600,2.778100,63.000000,58.000000,113.000000,131.200000,2.000000,4.500000
max,14.000000,2022.000000,63.230900,153.426500,240.000000,149.100000,3937.000000,377.300000,14.000000,12.000000